<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>9&nbsp; Regression II – Social Science Research Methods</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./resources.html" rel="next">
<link href="./08_regression.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./09_regression_ii.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">More Regression!</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Social Science Research Methods</a> 
    </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome to Lab Website</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_rbasics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">R Basics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_data_in_R.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data in R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_data_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Basic Data Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_pipe.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Functions, Libraries and Operators</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_reading.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">How to read a research article</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_crosstab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Cross Tabulation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07_correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Correlation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09_regression_ii.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">More Regression!</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./resources.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Resources</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#preliminaries" id="toc-preliminaries" class="nav-link active" data-scroll-target="#preliminaries"><span class="header-section-number">9.1</span> Preliminaries</a></li>
  <li><a href="#dealing-with-categorical-variables" id="toc-dealing-with-categorical-variables" class="nav-link" data-scroll-target="#dealing-with-categorical-variables"><span class="header-section-number">9.2</span> Dealing with categorical variables</a></li>
  <li><a href="#running-regression-with-a-categorical-variable" id="toc-running-regression-with-a-categorical-variable" class="nav-link" data-scroll-target="#running-regression-with-a-categorical-variable"><span class="header-section-number">9.3</span> Running regression with a categorical variable</a>
  <ul class="collapse">
  <li><a href="#changing-the-baseline-category" id="toc-changing-the-baseline-category" class="nav-link" data-scroll-target="#changing-the-baseline-category"><span class="header-section-number">9.3.1</span> Changing the baseline category</a></li>
  <li><a href="#task-1-run-a-regression-with-marker" id="toc-task-1-run-a-regression-with-marker" class="nav-link" data-scroll-target="#task-1-run-a-regression-with-marker"><span class="header-section-number">9.3.2</span> Task 1: Run a regression with marker</a></li>
  </ul></li>
  <li><a href="#multivariate-regression" id="toc-multivariate-regression" class="nav-link" data-scroll-target="#multivariate-regression"><span class="header-section-number">9.4</span> Multivariate regression</a>
  <ul class="collapse">
  <li><a href="#controlling-for-attendance-rate" id="toc-controlling-for-attendance-rate" class="nav-link" data-scroll-target="#controlling-for-attendance-rate"><span class="header-section-number">9.4.1</span> Controlling for Attendance Rate</a></li>
  </ul></li>
  <li><a href="#regression-table" id="toc-regression-table" class="nav-link" data-scroll-target="#regression-table"><span class="header-section-number">9.5</span> Regression Table</a></li>
  <li><a href="#r-squared" id="toc-r-squared" class="nav-link" data-scroll-target="#r-squared"><span class="header-section-number">9.6</span> R-squared</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Regression II</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>In this lab, we will work on a dataset named exam_marks. We have already seen this dataset in the last lecture. It is available on the module Blackboard. Alternatively, you can download it using this <a href="https://www.barisari.net/assets/data/mse/world_in_2010.csv">link</a>.</p>
<p>Place the file under a suitable directory and set your workspace.</p>
<section id="preliminaries" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="preliminaries"><span class="header-section-number">9.1</span> Preliminaries</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Preliminaries ####</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># remove everything from the environment</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>())</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># set the working directory:</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"~/methods/"</span>) <span class="co"># adjust the directory address accordingly</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># require the packages </span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
</div>
<p>Let’s import the dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import the dataset: Exam Marks #### </span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/exam_marks.csv"</span>) <span class="co"># load the data depending on the location on your comouter</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We have discussed this dataset in the lecture, but let’s quickly remind ourselves of the variables. Here is the codebook.</p>
<div id="tbl-demnatres2" class="cell striped hover quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-demnatres2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9.1: Exam Marks Dataset
</figcaption>
<div aria-describedby="tbl-demnatres2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="cell table-striped table-hover caption-top table table-sm small">
<colgroup>
<col style="width: 19%">
<col style="width: 39%">
<col style="width: 18%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th>Variable Name</th>
<th>Variable Explanation</th>
<th>Type of Variable</th>
<th>Possible Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>exam_id</td>
<td>ID of the exam</td>
<td>Numerical</td>
<td></td>
</tr>
<tr class="even">
<td>module_name</td>
<td>Name of the module</td>
<td>Categorical</td>
<td>French or Politics</td>
</tr>
<tr class="odd">
<td>marker_name</td>
<td>Name of the marker</td>
<td>Categorical</td>
<td>Alice, Bob, or Charlie</td>
</tr>
<tr class="even">
<td>attendance_student</td>
<td>Module attendance rate of the student</td>
<td>Numerical</td>
<td>0 – 100%</td>
</tr>
<tr class="odd">
<td>gpa_student</td>
<td>Overall GPA of the student (previous modules)</td>
<td>Numerical</td>
<td>0 – 100%</td>
</tr>
<tr class="even">
<td>mark</td>
<td>Exam mark</td>
<td>Numerical</td>
<td>0 – 100%</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>It is a good idea to use <code>summary()</code> to have a snapshot summary of the variables in the dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># summary of all variables:</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    exam_id       module_name        marker_name        attendance_student
 Min.   :240001   Length:100         Length:100         Min.   :  3.00    
 1st Qu.:240026   Class :character   Class :character   1st Qu.: 26.00    
 Median :240050   Mode  :character   Mode  :character   Median : 45.50    
 Mean   :240050                                         Mean   : 50.60    
 3rd Qu.:240075                                         3rd Qu.: 73.25    
 Max.   :240100                                         Max.   :100.00    
  gpa_student         mark      
 Min.   :39.10   Min.   :16.00  
 1st Qu.:56.45   1st Qu.:46.75  
 Median :63.34   Median :60.00  
 Mean   :64.38   Mean   :61.04  
 3rd Qu.:73.92   3rd Qu.:75.00  
 Max.   :89.78   Max.   :93.00  </code></pre>
</div>
</div>
<p>Note that the output displays the numerical summaries of four variables. However, two variables, <code>marker_name</code> and <code>module</code>, are stored as text. These are categorical variables. Let’s see how to deal with them.</p>
</section>
<section id="dealing-with-categorical-variables" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="dealing-with-categorical-variables"><span class="header-section-number">9.2</span> Dealing with categorical variables</h2>
<p>There are two categorical variables in this dataset: <code>marker_name</code> and <code>module</code>. They are stored as text. We will tell R to consider these as categorical variables, but first, let’s see the categories and respective frequencies.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># frequency table for marker name:</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(d<span class="sc">$</span>marker_name)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  Alice     Bob Charlie 
     32      35      33 </code></pre>
</div>
</div>
<p>There are three markers <em>Alice</em>, <em>Bob</em>, and <em>Charlie</em>. When you look at the variable, you can see that it is stored as text.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># let's check marker_name</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>d<span class="sc">$</span>marker_name <span class="sc">|&gt;</span> <span class="fu">head</span>(<span class="dv">5</span>) <span class="co"># show only the first 5 observations of marker</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Charlie" "Alice"   "Charlie" "Charlie" "Bob"    </code></pre>
</div>
</div>
<p>You can use <code>factor()</code> to tell R to consider this variable as a categorical variable. Let’s create a new variable <code>marker</code> and store the information in <code>marker_name</code> as a categorical variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># generate a new variable called marker: it is a categorical variable</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>d<span class="sc">$</span>marker <span class="ot">&lt;-</span> <span class="fu">factor</span>(d<span class="sc">$</span>marker_name)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s see how this variable is different from <code>marker_name</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Display first five observations of marker:</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>d<span class="sc">$</span>marker <span class="sc">|&gt;</span> <span class="fu">head</span>(<span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] Charlie Alice   Charlie Charlie Bob    
Levels: Alice Bob Charlie</code></pre>
</div>
</div>
<p>Carefully look at the output above. Observations are no longer enclosed in quotation marks. They are now treated as categories of a categorical variable rather than textual data. Most importantly, the output now displays <code>Levels:</code> and respective categories. The first category, in this case, <em>Alice</em> will be the baseline in a regression analysis.</p>
<p>You can also see the difference using <code>class()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(d<span class="sc">$</span>marker) <span class="co"># class of marker should be factor (meaning categorical)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "factor"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(d<span class="sc">$</span>marker_name) <span class="co"># class of marker_name is character (textual information)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "character"</code></pre>
</div>
</div>
<p>You can also use the <code>summary()</code> function again to see the difference.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># summary of all variables:</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    exam_id       module_name        marker_name        attendance_student
 Min.   :240001   Length:100         Length:100         Min.   :  3.00    
 1st Qu.:240026   Class :character   Class :character   1st Qu.: 26.00    
 Median :240050   Mode  :character   Mode  :character   Median : 45.50    
 Mean   :240050                                         Mean   : 50.60    
 3rd Qu.:240075                                         3rd Qu.: 73.25    
 Max.   :240100                                         Max.   :100.00    
  gpa_student         mark           marker  
 Min.   :39.10   Min.   :16.00   Alice  :32  
 1st Qu.:56.45   1st Qu.:46.75   Bob    :35  
 Median :63.34   Median :60.00   Charlie:33  
 Mean   :64.38   Mean   :61.04               
 3rd Qu.:73.92   3rd Qu.:75.00               
 Max.   :89.78   Max.   :93.00               </code></pre>
</div>
</div>
<p>Notice that the output for <code>marker</code> displays the frequencies of the groups, whereas <code>marker_name</code> just says character. You can also check if respective categories overlap.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(d<span class="sc">$</span>marker_name, d<span class="sc">$</span>marker)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         
          Alice Bob Charlie
  Alice      32   0       0
  Bob         0  35       0
  Charlie     0   0      33</code></pre>
</div>
</div>
<p>Next, it is time to tell R to store the information in <code>module_name</code> in a categorical variable called <code>module</code>. Try to do it yourself first before seeing the code below.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># module: a factor variable</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>d<span class="sc">$</span>module <span class="ot">&lt;-</span> <span class="fu">factor</span>(d<span class="sc">$</span>module_name)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Let’s see the new variable (and categories). The first category shown in Levels will be the default baseline in any regression analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co">#  See the categories: Levels tell the categories. </span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>d<span class="sc">$</span>module <span class="sc">|&gt;</span> <span class="fu">head</span>(<span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] Politics Politics Politics Politics French  
Levels: French Politics</code></pre>
</div>
</div>
<p>It is a good idea to check if the information recorded is the same.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># table  of : </span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(d<span class="sc">$</span>module_name, d<span class="sc">$</span>module)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          
           French Politics
  French       50        0
  Politics      0       50</code></pre>
</div>
</div>
</section>
<section id="running-regression-with-a-categorical-variable" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="running-regression-with-a-categorical-variable"><span class="header-section-number">9.3</span> Running regression with a categorical variable</h2>
<p>Let’s follow the order in the lecture and run a regression of <code>mark</code> on <code>module</code>. The regression equation is below:</p>
<p><span class="math display">\[ \hat{y} = \alpha + \beta \cdot Module \]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># regression: </span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(mark <span class="sc">~</span> module, <span class="at">data =</span> d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mark ~ module, data = d)

Coefficients:
   (Intercept)  modulePolitics  
         58.54            5.00  </code></pre>
</div>
</div>
<p>Regression output returned two coefficients: <code>(Intercept)</code> and <code>modulePolitics</code>. To use <code>module</code> in the regression analysis, R automatically picked one category as baseline ( <em>French</em> in this case) and turned the other category (<em>Politics</em>) into a binary variable. The regression equation turns into:</p>
<p><span class="math display">\[ \hat{y} = \alpha + \beta \cdot Politics \]</span></p>
<p><span class="math display">\[ 1. \text{ When the module is Politics: } Politics =  1 \]</span></p>
<p><span class="math display">\[ \hat{y} = \alpha + \beta \cdot 1 \]</span> <span class="math display">\[ \hat{y} = \alpha + \beta \]</span></p>
<p><span class="math display">\[ \hat{y} = 58.54 + 5.00 \]</span></p>
<p><span class="math display">\[ \hat{y} = 63.54 \]</span></p>
<p><span class="math display">\[ 2. \text{ When the module is French: } Politics = 0 \]</span></p>
<p><span class="math display">\[ \hat{y} = \alpha + \beta \cdot 0 \]</span> <span class="math display">\[ \hat{y} = \alpha  \]</span> <span class="math display">\[ \hat{y} = 58.54  \]</span> Recall from the last week that regression returns conditional means in a bivariate analysis with discrete values. Let’s write the respective coefficients and see if this is the case.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>d <span class="sc">|&gt;</span> <span class="fu">group_by</span>(module) <span class="sc">|&gt;</span> <span class="fu">summarise</span>(<span class="at">module_means =</span> <span class="fu">mean</span>(mark))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  module   module_means
  &lt;fct&gt;           &lt;dbl&gt;
1 French           58.5
2 Politics         63.5</code></pre>
</div>
</div>
<section id="changing-the-baseline-category" class="level3" data-number="9.3.1">
<h3 data-number="9.3.1" class="anchored" data-anchor-id="changing-the-baseline-category"><span class="header-section-number">9.3.1</span> Changing the baseline category</h3>
<p>Let’s say, we would like to make <em>French</em> as the baseline and see the coefficient for <em>Politics</em>. We can do this by <code>relevel()</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># redefine the baseline level (overwrite the existing variable): </span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>d<span class="sc">$</span>module <span class="ot">&lt;-</span> <span class="fu">relevel</span>(d<span class="sc">$</span>module, <span class="at">ref =</span> <span class="st">"French"</span>)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="co"># run the regression again:</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(mark <span class="sc">~</span> module, <span class="at">data =</span> d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mark ~ module, data = d)

Coefficients:
   (Intercept)  modulePolitics  
         58.54            5.00  </code></pre>
</div>
</div>
</section>
<section id="task-1-run-a-regression-with-marker" class="level3" data-number="9.3.2">
<h3 data-number="9.3.2" class="anchored" data-anchor-id="task-1-run-a-regression-with-marker"><span class="header-section-number">9.3.2</span> Task 1: Run a regression with marker</h3>
<ul>
<li>Run a regression of mark on marker. Interpret the results:</li>
</ul>
<p><span class="math display">\[ \hat{y} = \alpha + \beta \cdot Marker \]</span></p>
<div class="cell">
<details class="code-fold">
<summary>Show/Hide the Answer (R Code)</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># run the regression: </span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(mark <span class="sc">~</span> marker, <span class="at">data =</span> d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<ul>
<li>Make <em>Bob</em> the baseline category and run the regression again. Interpret the results.</li>
</ul>
<div class="cell">
<details class="code-fold">
<summary>Show/Hide the Answer (R Code)</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># redefine the baseline level (overwrite the existing variable): </span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>d<span class="sc">$</span>marker <span class="ot">&lt;-</span> <span class="fu">relevel</span>(d<span class="sc">$</span>marker, <span class="at">ref =</span> <span class="st">"Bob"</span>)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="co"># run the regression again:</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(mark <span class="sc">~</span> marker, <span class="at">data =</span> d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
</section>
<section id="multivariate-regression" class="level2" data-number="9.4">
<h2 data-number="9.4" class="anchored" data-anchor-id="multivariate-regression"><span class="header-section-number">9.4</span> Multivariate regression</h2>
<p>Next, we will run a series of regression models with multiple controls. Let’s say we are interested in the impact <code>student_gpa</code> on their expected <code>mark</code>. Without any controls, the bivariate regression model is as follows:</p>
<p><span id="eq-form1"><span class="math display">\[ \hat{y} = \alpha + \beta \cdot GPA  \tag{9.1}\]</span></span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># model 1: only gpa</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(mark <span class="sc">~</span> gpa_student, <span class="at">data =</span> d)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="co"># see the regression coefficients:</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>m1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mark ~ gpa_student, data = d)

Coefficients:
(Intercept)  gpa_student  
    -14.368        1.171  </code></pre>
</div>
</div>
<ul>
<li>According to Model 1, one point increase in the student GPA is associated with <strong>1.171</strong> points increase in the expected mark.</li>
</ul>
<p>However, GPA is not the only factor influencing the expected value of the outcome variable. We also know that who the marker is important. Compared to <em>Alice</em> and <em>Charlie</em>, <em>Bob</em> is a more generous marker, giving higher marks on average.</p>
<p>How to account for the impact of <code>marker</code>? We could divide the dataset into three by marker and run three regression models. This approach is possible, but it would be long and cumbersome. We will also have three different estimates for the impact of <code>gpa_student</code>, depending on the <code>marker</code>. This is shown in the block below.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Dividing the dataset by marker
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># divide the dataset into three (by marker)</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>alice   <span class="ot">&lt;-</span> d[d<span class="sc">$</span>marker <span class="sc">==</span> <span class="st">"Alice"</span>, ]</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>bob     <span class="ot">&lt;-</span> d[d<span class="sc">$</span>marker <span class="sc">==</span> <span class="st">"Bob"</span>, ]</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>charlie <span class="ot">&lt;-</span> d[d<span class="sc">$</span>marker <span class="sc">==</span> <span class="st">"Charlie"</span>, ]</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a><span class="co"># three regression models: </span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>m_alice   <span class="ot">&lt;-</span> <span class="fu">lm</span>(mark <span class="sc">~</span> gpa_student, <span class="at">data =</span> alice)</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>m_bob     <span class="ot">&lt;-</span> <span class="fu">lm</span>(mark <span class="sc">~</span> gpa_student, <span class="at">data =</span> bob)</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>m_charlie <span class="ot">&lt;-</span> <span class="fu">lm</span>(mark <span class="sc">~</span> gpa_student, <span class="at">data =</span> charlie)</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a><span class="co"># see each output:</span></span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>m_alice <span class="co"># model for alice</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mark ~ gpa_student, data = alice)

Coefficients:
(Intercept)  gpa_student  
    -22.953        1.216  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>m_bob <span class="co"># model for bob</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mark ~ gpa_student, data = bob)

Coefficients:
(Intercept)  gpa_student  
     -5.090        1.115  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>m_charlie <span class="co"># model for charlie</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mark ~ gpa_student, data = charlie)

Coefficients:
(Intercept)  gpa_student  
    -14.451        1.166  </code></pre>
</div>
</div>
<ul>
<li>When the marker is <em>Alice</em>, one point of increase in a student’s gpa is associated with 1.22 points of increase in their expected exam mark.</li>
<li>When the marker is <em>Bob</em>, one point of increase in a student’s gpa is associated with 1.12 points of increase in their expected exam mark.</li>
<li>When the marker is <em>Charlie</em>, one point of increase in a student’s gpa is associated with 1.17 points of increase in their expected exam mark.</li>
</ul>
</div>
</div>
</div>
<p>Instead of splitting the dataset into three pieces, a better approach is to consider <code>marker</code> in our regression model directly. In <a href="#eq-form2" class="quarto-xref">Equation&nbsp;<span>9.2</span></a> below, we are introducing <code>marker</code> as another variable influencing the expected value of our outcome variable, <code>mark</code>.</p>
<p><span id="eq-form2"><span class="math display">\[ \hat{y} = \alpha + \beta_1 \cdot GPA +  \beta_2 \cdot Marker  \tag{9.2}\]</span></span></p>
<p>Using <a href="#eq-form2" class="quarto-xref">Equation&nbsp;<span>9.2</span></a>, we can have one estimate for the impact of <code>gpa_student</code> while considering the impact of <code>marker</code>. In other words, we are <em>controlling for</em> <code>marker</code>.</p>
<p>Let’s run Model 2:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># model 2: gpa and marker</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(mark <span class="sc">~</span> gpa_student <span class="sc">+</span> marker, <span class="at">data =</span> d)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a><span class="co"># see the model 2:</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>m2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mark ~ gpa_student + marker, data = d)

Coefficients:
  (Intercept)    gpa_student    markerAlice  markerCharlie  
       -8.005          1.160        -11.305         -6.032  </code></pre>
</div>
</div>
<ul>
<li>According to Model 2, one point increase in the student GPA is associated with <strong>1.16 points</strong> increase in the expected mark, controlling for the marker.</li>
</ul>
<p>After considering who the marker is, there is a tiny change in the expected mark.</p>
<section id="controlling-for-attendance-rate" class="level3" data-number="9.4.1">
<h3 data-number="9.4.1" class="anchored" data-anchor-id="controlling-for-attendance-rate"><span class="header-section-number">9.4.1</span> Controlling for Attendance Rate</h3>
<p>Next, we will consider the attendance rate of a student. As we have seen in the lecture, there is good reason to expect that <code>gpa_student</code> and <code>attendance_student</code> are correlated, even though a student’s previous marks in different modules have no direct impact on their attendance rate for the current module. However, how hardworking a student is is a factor that influences both <code>gpa_student</code> and <code>attendance_rate</code>, linking the two variables. We can simply refer this underlying influence as student effort. Note that student effort is unobservable. <a href="#fig-dgp" class="quarto-xref">Figure&nbsp;<span>9.1</span></a> is an excerpt from the lecture slides, reflecting our theory.</p>
<div id="fig-dgp" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-dgp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<img src="images/data_generating_process.png" id="fig-surus" class="img-fluid figure-img">
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dgp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.1: Data generating process according to our theory. The dotted line represents correlation.
</figcaption>
</figure>
</div>
<p>In Model 3, we will add <code>attendance_student</code> as another predictor variable.</p>
<p><span id="eq-form3"><span class="math display">\[ \hat{y} = \alpha + \beta_1 \cdot GPA +  \beta_2 \cdot Marker + \beta_3 \cdot Attendance   \tag{9.3}\]</span></span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Model 3: Adding attendance to the module</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(mark <span class="sc">~</span> gpa_student <span class="sc">+</span> marker <span class="sc">+</span> attendance_student, <span class="at">data =</span> d)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a><span class="co"># see the model 3 coefficients:</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>m3<span class="sc">$</span>coefficients <span class="sc">|&gt;</span> <span class="fu">round</span>(<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       (Intercept)        gpa_student        markerAlice      markerCharlie 
             18.62               0.40             -11.56              -7.18 
attendance_student 
              0.44 </code></pre>
</div>
</div>
<p>Let’s pay close attention to the coefficients from Model 3, particularly to <code>gpa_student</code> and <code>attendance_student</code>.</p>
<ul>
<li>According to Model 3, one point increase in the <strong>student GPA</strong> is associated with <strong>0.40 points</strong> increase in the expected mark, controlling for the marker and the attendance rate.</li>
<li>According to Model 3, one point increase in the <strong>attendance rate</strong> is associated with <strong>0.44 points</strong> increase in the expected mark, controlling for the marker and the student gpa.</li>
</ul>
<p>Let’s compare Model 3 to Model 2: in Model 2, the estimated impact of <code>gpa_student</code> is almost three times higher than in Model 3. In other words, after controlling for <code>attendance_student</code>, the estimated impact of <code>gpa_student</code> is reduced by more than half.</p>
<p>If we do not control for the attendance rate, the GPA also captures the impact of the attendance rate. This is because GPA and attendance rate are correlated.</p>
<p>If we run a fourth model with only <code>attendance_student</code>, we will overestimate the impact of the attendance rate because it will capture the impact of the student gpa:</p>
<p><span id="eq-form4"><span class="math display">\[ \hat{y} = \alpha + \beta \cdot Attendance \tag{9.4}\]</span></span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># model 4: </span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>m4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(mark <span class="sc">~</span> attendance_student, <span class="at">data =</span> d)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="co"># see the coefficeints:</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>m4<span class="sc">$</span>coefficients <span class="sc">|&gt;</span> <span class="fu">round</span>(<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       (Intercept) attendance_student 
             32.85               0.56 </code></pre>
</div>
</div>
<p>Note that the estimated impact of <code>attendance_student</code> in Model 4 is increased to 0.56 (from 0.44 in Model 3). If we do not control for the student GPA, the attendance rate also captures the impact of the GPA.</p>
<p>For completeness, let’s run Models 5:</p>
<p><span id="eq-form5"><span class="math display">\[ \hat{y} = \alpha + \beta_1 \cdot GPA +  \beta_2 \cdot Marker + \beta_3 \cdot Attendance   + \beta_4 \cdot Module \tag{9.5}\]</span></span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># model 5: </span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>m5 <span class="ot">&lt;-</span> <span class="fu">lm</span>(mark <span class="sc">~</span> gpa_student <span class="sc">+</span> marker <span class="sc">+</span> attendance_student <span class="sc">+</span> module, <span class="at">data =</span> d)</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a><span class="co"># see the model 5:</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>m5</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mark ~ gpa_student + marker + attendance_student + 
    module, data = d)

Coefficients:
       (Intercept)         gpa_student         markerAlice       markerCharlie  
           16.9668              0.4175            -11.7748             -7.6233  
attendance_student      modulePolitics  
            0.4337              3.0767  </code></pre>
</div>
</div>
</section>
</section>
<section id="regression-table" class="level2" data-number="9.5">
<h2 data-number="9.5" class="anchored" data-anchor-id="regression-table"><span class="header-section-number">9.5</span> Regression Table</h2>
<p>As we have seen in the lecture, there is a standard way to report regression outputs. We will use <code>texreg</code> package to produce high-quality regression tables.</p>
<p>T</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install the package (only once):</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"texreg"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># call for the package:</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(texreg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Version:  1.39.4
Date:     2024-07-23
Author:   Philip Leifeld (University of Manchester)

Consider submitting praise using the praise or praise_interactive functions.
Please cite the JSS article in your publications -- see citation("texreg").</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'texreg'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:tidyr':

    extract</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># show a regression table on the screen: for model 1</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">screenreg</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
=======================
             Model 1   
-----------------------
(Intercept)  -14.37 *  
              (7.13)   
gpa_student    1.17 ***
              (0.11)   
-----------------------
R^2            0.54    
Adj. R^2       0.54    
Num. obs.    100       
=======================
*** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># for multiple models:</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="fu">screenreg</span>(<span class="fu">list</span>(m1, m2, m3, m4, m5))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
==============================================================================
                    Model 1     Model 2     Model 3     Model 4     Model 5   
------------------------------------------------------------------------------
(Intercept)         -14.37 *     -8.00       18.62 ***   32.85 ***   16.97 ***
                     (7.13)      (7.03)      (4.72)      (1.89)      (4.69)   
gpa_student           1.17 ***    1.16 ***    0.40 ***                0.42 ***
                     (0.11)      (0.10)      (0.09)                  (0.08)   
markerAlice                     -11.30 ***  -11.56 ***              -11.77 ***
                                 (2.84)      (1.72)                  (1.69)   
markerCharlie                    -6.03 *     -7.18 ***               -7.62 ***
                                 (2.84)      (1.72)                  (1.70)   
attendance_student                            0.44 ***    0.56 ***    0.43 ***
                                             (0.03)      (0.03)      (0.03)   
modulePolitics                                                        3.08 *  
                                                                     (1.40)   
------------------------------------------------------------------------------
R^2                   0.54        0.61        0.86        0.75        0.86    
Adj. R^2              0.54        0.59        0.85        0.75        0.86    
Num. obs.           100         100         100         100         100       
==============================================================================
*** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co"># to change the names of the variables</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>table_var_names <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Intercept"</span>, </span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>                     <span class="st">"Student GPA"</span>, </span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>                     <span class="st">"Marker: Alice"</span>, </span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>                     <span class="st">"Marker: Charlie"</span>,</span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>                     <span class="st">"Attendance Rate"</span>,</span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a>                     <span class="st">"Module: Politics"</span></span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a>                     )</span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a><span class="co"># screen reg:</span></span>
<span id="cb60-11"><a href="#cb60-11" aria-hidden="true" tabindex="-1"></a><span class="fu">screenreg</span>(<span class="fu">list</span>(m1, m2, m3, m4, m5), <span class="at">custom.coef.names =</span> table_var_names)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
============================================================================
                  Model 1     Model 2     Model 3     Model 4     Model 5   
----------------------------------------------------------------------------
Intercept         -14.37 *     -8.00       18.62 ***   32.85 ***   16.97 ***
                   (7.13)      (7.03)      (4.72)      (1.89)      (4.69)   
Student GPA         1.17 ***    1.16 ***    0.40 ***                0.42 ***
                   (0.11)      (0.10)      (0.09)                  (0.08)   
Marker: Alice                 -11.30 ***  -11.56 ***              -11.77 ***
                               (2.84)      (1.72)                  (1.69)   
Marker: Charlie                -6.03 *     -7.18 ***               -7.62 ***
                               (2.84)      (1.72)                  (1.70)   
Attendance Rate                             0.44 ***    0.56 ***    0.43 ***
                                           (0.03)      (0.03)      (0.03)   
Module: Politics                                                    3.08 *  
                                                                   (1.40)   
----------------------------------------------------------------------------
R^2                 0.54        0.61        0.86        0.75        0.86    
Adj. R^2            0.54        0.59        0.85        0.75        0.86    
Num. obs.         100         100         100         100         100       
============================================================================
*** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05</code></pre>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co"># you can also change the Model Names</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="fu">screenreg</span>(<span class="fu">list</span>(m_alice, m_bob, m_charlie),</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">custom.model.names =</span> <span class="fu">c</span>(<span class="st">"Alice"</span>, <span class="st">"Bob"</span>, <span class="st">"Charlie"</span>)</span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>          )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
===============================================
             Alice       Bob         Charlie   
-----------------------------------------------
(Intercept)  -22.95       -5.09      -14.45    
             (14.02)     (11.12)     (10.50)   
gpa_student    1.22 ***    1.12 ***    1.17 ***
              (0.21)      (0.17)      (0.17)   
-----------------------------------------------
R^2            0.52        0.58        0.62    
Adj. R^2       0.50        0.56        0.60    
Num. obs.     32          35          33       
===============================================
*** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co"># to save the regression outout as a word file:</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="fu">wordreg</span>(<span class="fu">list</span>(m1, m2, m3, m4, m5), <span class="st">"regression_table.docx"</span>,</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">custom.coef.names =</span> table_var_names)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>

processing file: file1f5a4a1d583e.Rmd</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>1/1 [unnamed-chunk-64]</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>output file: file1f5a4a1d583e.knit.md</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>/Applications/quarto/bin/tools/pandoc +RTS -K512m -RTS file1f5a4a1d583e.knit.md --to docx --from markdown+autolink_bare_uris+tex_math_single_backslash --output /Users/baris/Dropbox/teaching_research_methods/website_teaching/regression_table.docx --lua-filter /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/rmarkdown/rmarkdown/lua/pagebreak.lua --highlight-style tango </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Output created: regression_table.docx</code></pre>
</div>
</div>
</section>
<section id="r-squared" class="level2" data-number="9.6">
<h2 data-number="9.6" class="anchored" data-anchor-id="r-squared"><span class="header-section-number">9.6</span> R-squared</h2>
<p>We run five regression so far. Each regression model brings slightly (or sometimes largely) different estimates. How should we decide between different models? Your theory should guide your modelling strategy, but sometimes theory is silent or insufficient. In those cases, you can rely on regression metrics.</p>
<p>R-squared is a measure of how well the regression model accounts for the variation in the outcome variable. It is a measure between 0 (0.00%) and 1 (100.00%).</p>
<p>In Model 5, 86% of the variation in <code>mark</code> is explained by the regression model. You can see this by looking at <span class="math inline">\(R^2\)</span> in a regression table.</p>
<p>R-squared is non-decreasing. It always increases (or stays the same) when you introduce a new variable to the regression model. This is the case whether the new variable makes any sense or not.</p>
<p>However, we would like to be as parsimonious as possible. We want to explain as much as we can with as little as necessary.</p>
<p>Adjusted R-squared introduces a penalty for each variable added to the model. If a new variable does not bring sufficient improvement, the adjusted R-squared may decrease (or stay the same).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="co"># a nonsensical model</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>m_nonsense <span class="ot">&lt;-</span> <span class="fu">lm</span>(mark <span class="sc">~</span> gpa_student <span class="sc">+</span> exam_id, <span class="at">data =</span> d)</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a><span class="fu">screenreg</span>(<span class="fu">list</span>(m1, m_nonsense), <span class="at">custom.model.names =</span> <span class="fu">c</span>(<span class="st">"Model 1"</span>, <span class="st">"Nonsense"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
======================================
             Model 1     Nonsense     
--------------------------------------
(Intercept)  -14.37 *      4344.35    
              (7.13)     (10623.22)   
gpa_student    1.17 ***       1.16 ***
              (0.11)         (0.11)   
exam_id                      -0.02    
                             (0.04)   
--------------------------------------
R^2            0.54           0.54    
Adj. R^2       0.54           0.53    
Num. obs.    100            100       
======================================
*** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05</code></pre>
</div>
</div>
<p>Compared to Model 1, the nonsensical model performs worse. This is because <code>exam_id</code> is a roughly random number, having no relationship with exam mark.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./08_regression.html" class="pagination-link" aria-label="Regression">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Regression</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./resources.html" class="pagination-link" aria-label="Resources">
        <span class="nav-page-text">Resources</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>